# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: true

# see http://docs.travis-ci.com/user/installing-dependencies
before_install:
  - ./scripts/install-libsodium.sh
  - ./scripts/install-zeromq.sh

# see http://docs.travis-ci.com/user/languages/go/
language: go

script: scripts/03-test.sh

# vim: ts=2:sw=2 :                                                         

